spring:
    datasource:
        url: jdbc:mysql://localhost:3306/glamgest_db
        username: root
        password: p0p0QA1975..

    jpa:
        hibernate:
            ddl-auto: validate

        show-sql: true
