spring:
  datasource:
    # Corregido: Se agregó '_db' para coincidir con tu MySQL Workbench
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      # Valida que la base de datos coincida con las entidades
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  open-in-view: false

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

privacy-policy:
  version: ${PRIVACY_POLICY_VERSION:1.0}

email:
  service:
    url: ${EMAIL_SERVICE_URL:http://localhost:8081/api/email/send}

logging:
  level:
    com.glamgest.app: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/glamgest.log

google:
  recaptcha:
    secret-key: 6LdG2c0tAAAAALeHwn4T5zJNnmEO4Cd92uP6qjZv
    verify-url: https://www.google.com/recaptcha/api/siteverify
